export class ColumnasPlantillaExcel{
    TIPO_DOCUMENTO = 'TIPO_DOCUMENTO';
    NUMERO_DOCUMENTO = 'NUMERO_DOCUMENTO';
    PRIMER_NOMBRE = 'PRIMER_NOMBRE';
    SEGUNDO_NOMBRE = 'SEGUNDO_NOMBRE';
    PRIMER_APELLIDO	= 'PRIMER_APELLIDO'
    SEGUNDO_APELLIDO = 'SEGUNDO_APELLIDO'
    DIRECCION_RESIDENCIA = 'DIRECCION_RESIDENCIA'
    CELULAR_PRINCIPAL = 'CELULAR_PRINCIPAL'
    CELULAR_SECUNDARIO = 'CELULAR_SECUNDARIO'
    TELEFONO_FIJO = 'TELEFONO_FIJO'
}